version: '3'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/app/node_modules
      - ./frontend:/home/app
  tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./frontend:/home/app
    command: ["npm", "run", "test"]